### PR TITLE
issue15BizRankFirstCommit

### PR DESCRIPTION
**Pull request by avezqureshi14**
Pull Request for #issue15 Build the Card Component

### CODE REVIEW

**Comment by avezqureshi14** [comment]
ok @varisha-025

**Comment by varisha-025** [comment]
First please squash your commits into a single commit @avezqureshi14

**Comment by avezqureshi14** [comment]
ok @varisha-025

**Comment by avezqureshi14** [comment]
Hey @varisha-025 actually I am Unable to squash my merge commits do you have any solution for this

**Comment by varisha-025** [comment]
@avezqureshi14 let it be, I will squash it from my side. I am reviewing your PR right now.

**Comment by avezqureshi14** [comment]
Ok thank you @varisha-025

**Comment by varisha-025** [comment]
@avezqureshi14 I have reviewed your PR and requested some changes. Please do the changes as soon as possible.  Also, please follow the design attatched to the issue. Thanks.

**Comment by varisha-025** [comment]
@avezqureshi14 Have you seen the requested changes ?

**Comment by varisha-025** [comment]
@avezqureshi14 Please respond

**Comment by varisha-025** [comment]
@avezqureshi14 I will close your PR if you do not respond by today.

**Pull request closed without merging**
